### ISSUE TITLE
Recieve a mail on cancelation of signup

### ISSUE THREAD

**Issue by tv2-pvin** [anthiras/crimson#14]
As a user

I would like to receive an email when i cancel a signup confirming my cancelation

**Comment by anthiras** [comment]
Why? There is already a visual response to confirm your cancellation immediately (going from green signed up view to gray signup view).

**Comment by tv2-pvin** [comment]
If an instructor cancels the subscription the participant might not see it

**Comment by tv2-pvin** [comment]
yeah okay it's the same as issue #15 closing this one
